---
- name: Ensure SSH daemon is running
  service:
    name: "{{ ssh_sshd_name }}"
    state: "{{ ssh_sshd_state }}"

- name: Update SSH configuration to be more secure
  lineinfile:
    dest: "{{ ssh_config_path }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
    validate: 'sshd -T -f %s'
    mode: '0644'
  with_items:
    - regexp: "^PasswordAuthentication"
      line: "PasswordAuthentication {{ ssh_password_authentication }}"
    - regexp: "^PermitRootLogin"
      line: "PermitRootLogin {{ ssh_permit_root_login }}"
    - regexp: "^Port"
      line: "Port {{ ssh_port }}"
    - regexp: "^UseDNS"
      line: "UseDNS {{ ssh_usedns }}"
    - regexp: "^PermitEmptyPasswords"
      line: "PermitEmptyPasswords {{ ssh_permit_empty_password }}"
    - regexp: "^ChallengeResponseAuthentication"
      line: "ChallengeResponseAuthentication {{ ssh_challenge_response_auth }}"
    - regexp: "^GSSAPIAuthentication"
      line: "GSSAPIAuthentication {{ ssh_gss_api_authentication }}"
    - regexp: "^X11Forwarding"
      line: "X11Forwarding {{ ssh_x11_forwarding }}"
  notify:
    - reload systemd
    - restart ssh

- name: Add configured users allowed to connect over ssh
  lineinfile:
    dest: "{{ ssh_config_path }}"
    regexp: '^AllowUsers'
    line: "AllowUsers {{ ssh_allowed_users | join(' ') }}"
    state: present
    create: true
    validate: 'sshd -T -f %s'
    mode: '0644'
  when: ssh_allowed_users | length > 0
  notify: restart ssh

- name: Add configured groups allowed to connect over ssh
  lineinfile:
    dest: "{{ ssh_config_path }}"
    regexp: '^AllowGroups'
    line: "AllowGroups {{ ssh_allowed_groups | join(' ') }}"
    state: present
    create: true
    validate: 'sshd -T -f %s'
    mode: '0644'
  when: ssh_allowed_groups | length > 0
  notify: restart ssh

- name: Add configured user accounts to passwordless sudoers
  lineinfile:
    dest: /etc/sudoers
    regexp: '^{{ item }}'
    line: '{{ item }} ALL=(ALL) NOPASSWD: ALL'
    state: present
    validate: 'visudo -cf %s'
    mode: '0440'
  with_items: "{{ ssh_sudoers_passwordless }}"
  when: ssh_sudoers_passwordless | length > 0

- name: Add configured user accounts to passworded sudoers
  lineinfile:
    dest: /etc/sudoers
    regexp: '^{{ item }}'
    line: '{{ item }} ALL=(ALL) ALL'
    state: present
    validate: 'visudo -cf %s'
    mode: '0440'
  with_items: "{{ ssh_sudoers_passworded }}"
  when: ssh_sudoers_passworded | length > 0