- name: Update and upgarade System.
  apt: name=aptitude update_cache=yes state=present force_apt_get=yes

- name: Install VS Code from the internet
  ansible.builtin.apt:
    deb: https://vscode.download.prss.microsoft.com/dbazure/download/stable/4849ca9bdf9666755eb463db297b69e5385090e3/code_1.93.0-1725459079_amd64.deb

- name: Install Chrome from the internet
  ansible.builtin.apt:
    deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb