---
# Python version configuration
python_version: "3.12"
python_full_version: "3.12.9"
python_uninstall: false

# Python packages to install
python_packages:
  - "python{{ python_version }}"
  - "python{{ python_version }}-dev"
  - "python{{ python_version }}-venv"

# Deadsnakes PPA configuration
deadsnakes_ppa: "ppa:deadsnakes/ppa"