---
# SSH daemon configuration defaults

# SSH service name and state
ssh_sshd_name: ssh
ssh_sshd_state: started

# SSH configuration file path
ssh_config_path: /etc/ssh/sshd_config

# SSH security settings
ssh_port: 22
ssh_password_authentication: "no"
ssh_permit_root_login: "no"
ssh_usedns: "no"
ssh_permit_empty_password: "no"
ssh_challenge_response_auth: "no"
ssh_gss_api_authentication: "no"
ssh_x11_forwarding: "no"

# SSH access control
ssh_allowed_users: ["ubuntu"]
ssh_allowed_groups: []

# Sudoers configuration
ssh_sudoers_passwordless: []
ssh_sudoers_passworded: []