- name: playbook for localhost
  hosts: local
  remote_user: ubuntu
  become: True
  roles:
    # common
    # users
    # docker
    # openalpr
    - xapps
  tags: setup

- name: playbook for localhost
  hosts: local
  remote_user: ubuntu
  become: False
  roles:
    - nodejs
  tags: setupNodejs

- name: playbook for localhost
  hosts: local
  remote_user: ubuntu
  become: False
  roles:
    - dotfiles
  tags: setupDotfiles

- name: playbook for localhost
  hosts: local
  become: True
  roles:
    - pipx
  tags: setupPipx